on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest

  e2e:
    runs-on: ubuntu-latest

  lint:
    runs-on: ubuntu-latest

  build:
    runs-on: ubuntu-latest


  


